apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: raj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx          
    spec:
      containers:
      - env:
        image: 0.0.0.0:4010/nginx:NGINX_CICD-20-10-2021-08-21
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
